---
development:
  cloud_name: davxftlci
  api_key: '326912184746193'
  api_secret: N37sWp5EqpxtQM_pTLVx5euEOJg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: davxftlci
  api_key: '326912184746193'
  api_secret: N37sWp5EqpxtQM_pTLVx5euEOJg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: davxftlci
  api_key: '326912184746193'
  api_secret: N37sWp5EqpxtQM_pTLVx5euEOJg
  enhance_image_tag: true
  static_image_support: false
